//
//  Bank.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Bank: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _last4Digits: String?
    var _isCreditCard: NSNumber?
    var _name: String?
    
    class func dynamoDBTableName() -> String {

        return "mypayments-mobilehub-916445320-Bank"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_last4Digits"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_last4Digits" : "last4Digits",
               "_isCreditCard" : "isCreditCard",
               "_name" : "name",
        ]
    }
}
