//
//  Transaction.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Transaction: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _bankName: String?
    var _spentOn: String?
    var _addedOn: String?
    var _amount: NSNumber?
    var _cardLast4Digits: NSNumber?
    var _modifiedOn: String?
    var _notes: String?
    
    class func dynamoDBTableName() -> String {

        return "mypayments-mobilehub-317933950-Transaction"
    }
    
    class func hashKeyAttribute() -> String {

        return "_bankName"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_spentOn"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_bankName" : "bankName",
               "_spentOn" : "spentOn",
               "_addedOn" : "addedOn",
               "_amount" : "amount",
               "_cardLast4Digits" : "cardLast4Digits",
               "_modifiedOn" : "modifiedOn",
               "_notes" : "notes",
        ]
    }
}
