//
//  Bank.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Bank: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _id: String?
    @objc var _createdOn: String?
    @objc var _isCreditCard: NSNumber?
    @objc var _last4Digits: NSNumber?
    @objc var _modifiedOn: String?
    @objc var _name: String?
    
    class func dynamoDBTableName() -> String {

        return "mypayments-mobilehub-317933950-Bank"
    }
    
    class func hashKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_id" : "id",
               "_createdOn" : "createdOn",
               "_isCreditCard" : "isCreditCard",
               "_last4Digits" : "last4Digits",
               "_modifiedOn" : "modifiedOn",
               "_name" : "name",
        ]
    }
}
