//
//  Transaction.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Transaction: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _spentOn: String?
    @objc var _addedOn: String?
    @objc var _amount: NSNumber?
    @objc var _associatedBankId: String?
    @objc var _modifiedOn: String?
    @objc var _notes: String?
    @objc var _s3ImageKey: String?
    
    class func dynamoDBTableName() -> String {

        return "mypayments-mobilehub-317933950-Transaction"
    }
    
    class func hashKeyAttribute() -> String {

        return "_spentOn"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_spentOn" : "spentOn",
               "_addedOn" : "addedOn",
               "_amount" : "amount",
               "_associatedBankId" : "associatedBankId",
               "_modifiedOn" : "modifiedOn",
               "_notes" : "notes",
               "_s3ImageKey" : "s3ImageKey",
        ]
    }
}
